@startuml ArbreSyntaxique
object "Procedure" as Procedure
object "unDebut" as unDebut
object "Bloc" as Bloc
object "Bloc" as Bloc3
object "Fonction" as Fonction
object "Fonction" as Fonction1
object "Instanciation" as Instanciation6
object "Affectation" as Affectation2
object "If" as InstructionIf
object "aireRectangle" as aireRectangle
object "Instanciation" as Instanciation
object "Instanciation" as Instanciation1
object "INTEGER" as INTEGER__
object "Instanciation" as Instanciation2
object "Bloc" as Bloc1
object "perimetreRectangle" as perimetreRectangle
object "Instanciation" as Instanciation3
object "Instanciation" as Instanciation4
object "INTEGER" as INTEGER______
object "Instanciation" as Instanciation5
object "Bloc" as Bloc2
object "choix" as choix
object "INTEGER" as INTEGER________
object "choix" as choix_
object "2" as 2__
object "Operation" as Operation4
object "Affectation" as Affectation3
object "Affectation" as Affectation4
object "larg" as larg
object "INTEGER" as INTEGER
object "long" as long
object "INTEGER" as INTEGER_
object "aire" as aire
object "INTEGER" as INTEGER___
object "Affectation" as Affectation
object "Return" as Return
object "larg" as larg__
object "INTEGER" as INTEGER____
object "long" as long__
object "INTEGER" as INTEGER_____
object "perimetre" as perimetre
object "INTEGER" as INTEGER_______
object "Affectation" as Affectation1
object "Return" as Return1
object "choix" as choix__
object "EGAL" as EGAL
object "1" as 1
object "valeur" as valeur
object "Appel Fonction" as AppelFonction
object "valeur" as valeur_
object "Appel Fonction" as AppelFonction1
object "aire" as aire_
object "Operation" as Operation
object "aire" as aire__
object "perimetre" as perimetre_
object "Operation" as Operation1
object "perimetre" as perimetre__
object "perimetreRectangle" as perimetreRectangle_
object "2" as 2___
object "3" as 3
object "aireRectangle" as aireRectangle_
object "2" as 2____
object "3" as 3_
object "larg" as larg_
object "FOIS" as FOIS
object "long" as long_
object "Operation" as Operation2
object "PLUS" as PLUS
object "Operation" as Operation3
object "larg" as larg___
object "FOIS" as FOIS_
object "2" as 2
object "long" as long___
object "FOIS" as FOIS__
object "2" as 2_
Procedure -down-> unDebut
Procedure -down-> Bloc
Procedure -down-> Bloc3
Bloc -down-> Fonction
Bloc -down-> Fonction1
Bloc -down-> Instanciation6
Bloc3 -down-> Affectation2
Bloc3 -down-> InstructionIf
Fonction -down-> aireRectangle
Fonction -down-> Instanciation
Fonction -down-> Instanciation1
Fonction -down-> INTEGER__
Fonction -down-> Instanciation2
Fonction -down-> Bloc1
Fonction1 -down-> perimetreRectangle
Fonction1 -down-> Instanciation3
Fonction1 -down-> Instanciation4
Fonction1 -down-> INTEGER______
Fonction1 -down-> Instanciation5
Fonction1 -down-> Bloc2
Instanciation6 -down-> choix
Instanciation6 -down-> INTEGER________
Affectation2 -down-> choix_
Affectation2 -down-> 2__
InstructionIf -down-> Operation4
InstructionIf -down-> Affectation3
InstructionIf -down-> Affectation4
Instanciation -down-> larg
Instanciation -down-> INTEGER
Instanciation1 -down-> long
Instanciation1 -down-> INTEGER_
Instanciation2 -down-> aire
Instanciation2 -down-> INTEGER___
Bloc1 -down-> Affectation
Bloc1 -down-> Return
Instanciation3 -down-> larg__
Instanciation3 -down-> INTEGER____
Instanciation4 -down-> long__
Instanciation4 -down-> INTEGER_____
Instanciation5 -down-> perimetre
Instanciation5 -down-> INTEGER_______
Bloc2 -down-> Affectation1
Bloc2 -down-> Return1
Operation4 -down-> choix__
Operation4 -down-> EGAL
Operation4 -down-> 1
Affectation3 -down-> valeur
Affectation3 -down-> AppelFonction
Affectation4 -down-> valeur_
Affectation4 -down-> AppelFonction1
Affectation -down-> aire_
Affectation -down-> Operation
Return -down-> aire__
Affectation1 -down-> perimetre_
Affectation1 -down-> Operation1
Return1 -down-> perimetre__
AppelFonction -down-> perimetreRectangle_
AppelFonction -down-> 2___
AppelFonction -down-> 3
AppelFonction1 -down-> aireRectangle_
AppelFonction1 -down-> 2____
AppelFonction1 -down-> 3_
Operation -down-> larg_
Operation -down-> FOIS
Operation -down-> long_
Operation1 -down-> Operation2
Operation1 -down-> PLUS
Operation1 -down-> Operation3
Operation2 -down-> larg___
Operation2 -down-> FOIS_
Operation2 -down-> 2
Operation3 -down-> long___
Operation3 -down-> FOIS__
Operation3 -down-> 2_
@enduml
