@startuml ArbreSyntaxique
object "Procedure" as Procedure
object "unDebut" as unDebut
object "Bloc" as Bloc
object "Bloc" as Bloc3
object "Fonction" as Fonction
object "Fonction" as Fonction1
object "Déclaration" as Declaration2
object "Affectation" as Affectation2
object "If" as InstructionIf
object "aireRectangle" as aireRectangle
object "Paramètre" as Parametre
object "Paramètre" as Parametre1
object "INTEGER" as INTEGER__
object "Déclaration" as Declaration
object "Bloc" as Bloc1
object "perimetreRectangle" as perimetreRectangle
object "Paramètre" as Parametre2
object "Paramètre" as Parametre3
object "INTEGER" as INTEGER______
object "Déclaration" as Declaration1
object "Bloc" as Bloc2
object "choix" as choix
object "INTEGER" as INTEGER________
object "choix" as choix_
object "2" as 2__
object "EGAL" as Operation4
object "Affectation" as Affectation3
object "Affectation" as Affectation4
object "larg" as larg
object "INTEGER" as INTEGER
object "long" as long
object "INTEGER" as INTEGER_
object "aire" as aire
object "INTEGER" as INTEGER___
object "Affectation" as Affectation
object "Return" as Return
object "larg" as larg__
object "INTEGER" as INTEGER____
object "long" as long__
object "INTEGER" as INTEGER_____
object "perimetre" as perimetre
object "INTEGER" as INTEGER_______
object "Affectation" as Affectation1
object "Return" as Return1
object "choix" as choix__
object "1" as 1
object "valeur" as valeur
object "Appel Fonction" as AppelFonction
object "valeur" as valeur_
object "Appel Fonction" as AppelFonction1
object "aire" as aire_
object "FOIS" as Operation
object "aire" as aire__
object "perimetre" as perimetre_
object "PLUS" as Operation1
object "perimetre" as perimetre__
object "perimetreRectangle" as perimetreRectangle_
object "2" as 2___
object "3" as 3
object "aireRectangle" as aireRectangle_
object "2" as 2____
object "3" as 3_
object "larg" as larg_
object "long" as long_
object "FOIS" as Operation2
object "FOIS" as Operation3
object "larg" as larg___
object "2" as 2
object "long" as long___
object "2" as 2_
Procedure -down-> unDebut
Procedure -down-> Bloc
Procedure -down-> Bloc3
Bloc -down-> Fonction
Bloc -down-> Fonction1
Bloc -down-> Declaration2
Bloc3 -down-> Affectation2
Bloc3 -down-> InstructionIf
Fonction -down-> aireRectangle
Fonction -down-> Parametre
Fonction -down-> Parametre1
Fonction -down-> INTEGER__
Fonction -down-> Declaration
Fonction -down-> Bloc1
Fonction1 -down-> perimetreRectangle
Fonction1 -down-> Parametre2
Fonction1 -down-> Parametre3
Fonction1 -down-> INTEGER______
Fonction1 -down-> Declaration1
Fonction1 -down-> Bloc2
Declaration2 -down-> choix
Declaration2 -down-> INTEGER________
Affectation2 -down-> choix_
Affectation2 -down-> 2__
InstructionIf -down-> Operation4
InstructionIf -down-> Affectation3
InstructionIf -down-> Affectation4
Parametre -down-> larg
Parametre -down-> INTEGER
Parametre1 -down-> long
Parametre1 -down-> INTEGER_
Declaration -down-> aire
Declaration -down-> INTEGER___
Bloc1 -down-> Affectation
Bloc1 -down-> Return
Parametre2 -down-> larg__
Parametre2 -down-> INTEGER____
Parametre3 -down-> long__
Parametre3 -down-> INTEGER_____
Declaration1 -down-> perimetre
Declaration1 -down-> INTEGER_______
Bloc2 -down-> Affectation1
Bloc2 -down-> Return1
Operation4 -down-> choix__
Operation4 -down-> 1
Affectation3 -down-> valeur
Affectation3 -down-> AppelFonction
Affectation4 -down-> valeur_
Affectation4 -down-> AppelFonction1
Affectation -down-> aire_
Affectation -down-> Operation
Return -down-> aire__
Affectation1 -down-> perimetre_
Affectation1 -down-> Operation1
Return1 -down-> perimetre__
AppelFonction -down-> perimetreRectangle_
AppelFonction -down-> 2___
AppelFonction -down-> 3
AppelFonction1 -down-> aireRectangle_
AppelFonction1 -down-> 2____
AppelFonction1 -down-> 3_
Operation -down-> larg_
Operation -down-> long_
Operation1 -down-> Operation2
Operation1 -down-> Operation3
Operation2 -down-> larg___
Operation2 -down-> 2
Operation3 -down-> long___
Operation3 -down-> 2_
@enduml
