@startuml Arbre_Syntaxique
object "£FICHIER" as 1
object "with" as 2
object "IDF" as 3
3 : ada
object "." as 4
object "IDF" as 5
5 : text_io
object "use" as 6
object "IDF" as 7
7 : ada
object "." as 8
object "IDF" as 9
9 : text_io
object "procedure" as 10
object "IDF" as 11
11 : fibonacci
object "is" as 12
object "£DECLEtoile" as 13
object "begin" as 14
object "£INSTR" as 15
object "£INSTR" as 16
object "end" as 17
object "IDF" as 18
18 : fibonacci
object "EOF" as 19
object "£DECL" as 20
object "£DECL" as 21
object "£DECL" as 22
object "IDF" as 23
23 : res
object "£DEFORInterro" as 24
object "IDF" as 25
25 : lol
object "£DEFORInterro" as 26
object "IDF" as 27
27 : n
object "IDF" as 28
28 : natural
object "£DEFORInterro" as 29
object "IDF" as 30
30 : res
object "IDF" as 31
31 : natural
object "£DEFORInterro" as 32
object "function" as 33
object "IDF" as 34
34 : fib
object "£PARENTHESE" as 35
object "return" as 36
object "IDF" as 37
37 : natural
object "is" as 38
object "begin" as 39
object "£INSTR" as 40
object "end" as 41
object "IDF" as 42
42 : fib
object ":=" as 43
object "£LVALUE" as 44
object ":=" as 45
object "entier" as 46
46 : 1
object ":=" as 47
object "entier" as 48
48 : 10
object ":=" as 49
object "entier" as 50
50 : 0
object "IDF" as 51
51 : n
object "IDF" as 52
52 : natural
object "if" as 53
object "£EQUALS" as 54
object "then" as 55
object "£INSTR" as 56
object "£ELSIFEtoile" as 57
object "£ELSEINSTRInterro" as 58
object "end" as 59
object "if" as 60
object "IDF" as 61
61 : fib
object "IDF" as 62
62 : n
object "£LVALUE" as 63
object "£MOINSUnaire" as 64
object "return" as 65
object "entier" as 66
66 : 0
object "elsif" as 67
object "£EQUALS" as 68
object "then" as 69
object "£INSTR" as 70
object "else" as 71
object "£INSTR" as 72
object "IDF" as 73
73 : n
object "£LVALUEList" as 74
object "-" as 75
object "entier" as 76
76 : 0
object "IDF" as 77
77 : n
object "entier" as 78
78 : 1
object "return" as 79
object "entier" as 80
80 : 1
object "return" as 81
object "£ADD" as 82
object "." as 83
object "IDF" as 84
84 : o
object "£LVALUE" as 85
object "+" as 86
object "£LVALUE" as 87
object "IDF" as 88
88 : fib
object "£ADD" as 89
object "IDF" as 90
90 : fib
object "£ADD" as 91
object "entier" as 92
92 : 2
object "-" as 93
object "IDF" as 94
94 : n
object "entier" as 95
95 : 1
object "-" as 96
object "IDF" as 97
97 : n
1 -down-> 2
1 -down-> 3
1 -down-> 4
1 -down-> 5
1 -down-> 6
1 -down-> 7
1 -down-> 8
1 -down-> 9
1 -down-> 10
1 -down-> 11
1 -down-> 12
1 -down-> 13
1 -down-> 14
1 -down-> 15
1 -down-> 16
1 -down-> 17
1 -down-> 18
1 -down-> 19
13 -down-> 20
13 -down-> 21
13 -down-> 22
15 -down-> 23
15 -down-> 24
16 -down-> 25
16 -down-> 26
20 -down-> 27
20 -down-> 28
20 -down-> 29
21 -down-> 30
21 -down-> 31
21 -down-> 32
22 -down-> 33
22 -down-> 34
22 -down-> 35
22 -down-> 36
22 -down-> 37
22 -down-> 38
22 -down-> 39
22 -down-> 40
22 -down-> 41
22 -down-> 42
24 -down-> 43
24 -down-> 44
26 -down-> 45
26 -down-> 46
29 -down-> 47
29 -down-> 48
32 -down-> 49
32 -down-> 50
35 -down-> 51
35 -down-> 52
40 -down-> 53
40 -down-> 54
40 -down-> 55
40 -down-> 56
40 -down-> 57
40 -down-> 58
40 -down-> 59
40 -down-> 60
44 -down-> 61
44 -down-> 62
54 -down-> 63
54 -down-> 64
56 -down-> 65
56 -down-> 66
57 -down-> 67
57 -down-> 68
57 -down-> 69
57 -down-> 70
58 -down-> 71
58 -down-> 72
63 -down-> 73
63 -down-> 74
64 -down-> 75
64 -down-> 76
68 -down-> 77
68 -down-> 78
70 -down-> 79
70 -down-> 80
72 -down-> 81
72 -down-> 82
74 -down-> 83
74 -down-> 84
82 -down-> 85
82 -down-> 86
82 -down-> 87
85 -down-> 88
85 -down-> 89
87 -down-> 90
87 -down-> 91
89 -down-> 92
89 -down-> 93
89 -down-> 94
91 -down-> 95
91 -down-> 96
91 -down-> 97
@enduml
