@startuml Arbre_Syntaxique
object "£FICHIER" as 1
object "with" as 2
object "IDF" as 3
3 : ada
object "." as 4
object "IDF" as 5
5 : text_io
object ";" as 6
object "use" as 7
object "IDF" as 8
8 : ada
object "." as 9
object "IDF" as 10
10 : text_io
object ";" as 11
object "procedure" as 12
object "IDF" as 13
13 : fibonacci
object "is" as 14
object "£DECLEtoile" as 15
object "begin" as 16
object "£INSTR" as 17
object "end" as 18
object "IDF" as 19
19 : fibonacci
object ";" as 20
object "EOF" as 21
object "£DECL" as 22
object "£DECL" as 23
object "£DECL" as 24
object "IDF" as 25
25 : res
object "£DEFORInterro" as 26
object ";" as 27
object "IDF" as 28
28 : n
object ":" as 29
object "IDF" as 30
30 : natural
object "£DEFORInterro" as 31
object ";" as 32
object "IDF" as 33
33 : res
object ":" as 34
object "IDF" as 35
35 : natural
object "£DEFORInterro" as 36
object ";" as 37
object "function" as 38
object "IDF" as 39
39 : fib
object "£PARENTHESE" as 40
object "return" as 41
object "IDF" as 42
42 : natural
object "is" as 43
object "begin" as 44
object "£INSTR" as 45
object "end" as 46
object "IDF" as 47
47 : fib
object ";" as 48
object ":=" as 49
object "£LVALUE" as 50
object ":=" as 51
object "entier" as 52
52 : 10
object ":=" as 53
object "entier" as 54
54 : 0
object "(" as 55
object "IDF" as 56
56 : n
object ":" as 57
object "IDF" as 58
58 : natural
object ")" as 59
object "if" as 60
object "£EQUALS" as 61
object "then" as 62
object "£INSTR" as 63
object "£ELSIFEtoile" as 64
object "£ELSEINSTRInterro" as 65
object "end" as 66
object "if" as 67
object ";" as 68
object "IDF" as 69
69 : fib
object "£LVALUEList" as 70
object "entier" as 71
71 : 0
object "IDF" as 72
72 : n
object "return" as 73
object "entier" as 74
74 : 0
object ";" as 75
object "elsif" as 76
object "£EQUALS" as 77
object "then" as 78
object "£INSTR" as 79
object "else" as 80
object "£INSTR" as 81
object "(" as 82
object "IDF" as 83
83 : n
object ")" as 84
object "entier" as 85
85 : 1
object "IDF" as 86
86 : n
object "return" as 87
object "entier" as 88
88 : 1
object ";" as 89
object "return" as 90
object "£ADD" as 91
object ";" as 92
object "£LVALUE" as 93
object "£LVALUE" as 94
object "IDF" as 95
95 : fib
object "£LVALUEList" as 96
object "IDF" as 97
97 : fib
object "£LVALUEList" as 98
object "(" as 99
object "£ADD" as 100
object ")" as 101
object "(" as 102
object "£ADD" as 103
object ")" as 104
object "entier" as 105
105 : 2
object "IDF" as 106
106 : n
object "entier" as 107
107 : 1
object "IDF" as 108
108 : n
1 -down-> 2
1 -down-> 3
1 -down-> 4
1 -down-> 5
1 -down-> 6
1 -down-> 7
1 -down-> 8
1 -down-> 9
1 -down-> 10
1 -down-> 11
1 -down-> 12
1 -down-> 13
1 -down-> 14
1 -down-> 15
1 -down-> 16
1 -down-> 17
1 -down-> 18
1 -down-> 19
1 -down-> 20
1 -down-> 21
15 -down-> 22
15 -down-> 23
15 -down-> 24
17 -down-> 25
17 -down-> 26
17 -down-> 27
22 -down-> 28
22 -down-> 29
22 -down-> 30
22 -down-> 31
22 -down-> 32
23 -down-> 33
23 -down-> 34
23 -down-> 35
23 -down-> 36
23 -down-> 37
24 -down-> 38
24 -down-> 39
24 -down-> 40
24 -down-> 41
24 -down-> 42
24 -down-> 43
24 -down-> 44
24 -down-> 45
24 -down-> 46
24 -down-> 47
24 -down-> 48
26 -down-> 49
26 -down-> 50
31 -down-> 51
31 -down-> 52
36 -down-> 53
36 -down-> 54
40 -down-> 55
40 -down-> 56
40 -down-> 57
40 -down-> 58
40 -down-> 59
45 -down-> 60
45 -down-> 61
45 -down-> 62
45 -down-> 63
45 -down-> 64
45 -down-> 65
45 -down-> 66
45 -down-> 67
45 -down-> 68
50 -down-> 69
50 -down-> 70
61 -down-> 71
61 -down-> 72
63 -down-> 73
63 -down-> 74
63 -down-> 75
64 -down-> 76
64 -down-> 77
64 -down-> 78
64 -down-> 79
65 -down-> 80
65 -down-> 81
70 -down-> 82
70 -down-> 83
70 -down-> 84
77 -down-> 85
77 -down-> 86
79 -down-> 87
79 -down-> 88
79 -down-> 89
81 -down-> 90
81 -down-> 91
81 -down-> 92
91 -down-> 93
91 -down-> 94
93 -down-> 95
93 -down-> 96
94 -down-> 97
94 -down-> 98
96 -down-> 99
96 -down-> 100
96 -down-> 101
98 -down-> 102
98 -down-> 103
98 -down-> 104
100 -down-> 105
100 -down-> 106
103 -down-> 107
103 -down-> 108
@enduml
