@startuml Arbre_Syntaxique
object "£FICHIER" as 1
object "with" as 2
object "IDF" as 3
3 : ada
object "." as 4
object "IDF" as 5
5 : text_io
object "use" as 6
object "IDF" as 7
7 : ada
object "." as 8
object "IDF" as 9
9 : text_io
object "procedure" as 10
object "IDF" as 11
11 : fibonacci
object "is" as 12
object "£DECLEtoile" as 13
object "begin" as 14
object "£INSTR" as 15
object "£INSTREtoile" as 16
object "end" as 17
object "IDF" as 18
18 : fibonacci
object "EOF" as 19
object "£DECL" as 20
object "£DECL" as 21
object "£DECL" as 22
object "IDF" as 23
23 : res
object "£DEFORInterro" as 24
object "£INSTR" as 25
object "£INSTR" as 26
object "IDF" as 27
27 : n
object "IDF" as 28
28 : natural
object "£DEFORInterro" as 29
object "IDF" as 30
30 : res
object "IDF" as 31
31 : natural
object "£DEFORInterro" as 32
object "function" as 33
object "IDF" as 34
34 : fib
object "£PARENTHESE" as 35
object "return" as 36
object "IDF" as 37
37 : natural
object "is" as 38
object "begin" as 39
object "£INSTR" as 40
object "end" as 41
object "IDF" as 42
42 : fib
object ":=" as 43
object "£LVALUE" as 44
object "IDF" as 45
45 : lol
object "£DEFORInterro" as 46
object "IDF" as 47
47 : ar
object "£DEFORInterro" as 48
object ":=" as 49
object "entier" as 50
50 : 10
object ":=" as 51
object "entier" as 52
52 : 0
object "IDF" as 53
53 : n
object "IDF" as 54
54 : natural
object "if" as 55
object "£EQUALS" as 56
object "then" as 57
object "£INSTR" as 58
object "£ELSIFEtoile" as 59
object "£ELSEINSTRInterro" as 60
object "end" as 61
object "if" as 62
object "IDF" as 63
63 : fib
object "IDF" as 64
64 : n
object ":=" as 65
object "entier" as 66
66 : 1
object ":=" as 67
object "entier" as 68
68 : 2
object "£LVALUE" as 69
object "£MOINSUnaire" as 70
object "return" as 71
object "entier" as 72
72 : 0
object "elsif" as 73
object "£EQUALS" as 74
object "then" as 75
object "£INSTR" as 76
object "else" as 77
object "£INSTR" as 78
object "IDF" as 79
79 : n
object "£LVALUEList" as 80
object "-" as 81
object "entier" as 82
82 : 0
object "IDF" as 83
83 : n
object "entier" as 84
84 : 1
object "return" as 85
object "entier" as 86
86 : 1
object "return" as 87
object "£ADD" as 88
object "." as 89
object "IDF" as 90
90 : o
object "£LVALUE" as 91
object "+" as 92
object "£LVALUE" as 93
object "IDF" as 94
94 : fib
object "£ADD" as 95
object "IDF" as 96
96 : fib
object "£ADD" as 97
object "entier" as 98
98 : 2
object "-" as 99
object "IDF" as 100
100 : n
object "entier" as 101
101 : 1
object "-" as 102
object "IDF" as 103
103 : n
1 -down-> 2
1 -down-> 3
1 -down-> 4
1 -down-> 5
1 -down-> 6
1 -down-> 7
1 -down-> 8
1 -down-> 9
1 -down-> 10
1 -down-> 11
1 -down-> 12
1 -down-> 13
1 -down-> 14
1 -down-> 15
1 -down-> 16
1 -down-> 17
1 -down-> 18
1 -down-> 19
13 -down-> 20
13 -down-> 21
13 -down-> 22
15 -down-> 23
15 -down-> 24
16 -down-> 25
16 -down-> 26
20 -down-> 27
20 -down-> 28
20 -down-> 29
21 -down-> 30
21 -down-> 31
21 -down-> 32
22 -down-> 33
22 -down-> 34
22 -down-> 35
22 -down-> 36
22 -down-> 37
22 -down-> 38
22 -down-> 39
22 -down-> 40
22 -down-> 41
22 -down-> 42
24 -down-> 43
24 -down-> 44
25 -down-> 45
25 -down-> 46
26 -down-> 47
26 -down-> 48
29 -down-> 49
29 -down-> 50
32 -down-> 51
32 -down-> 52
35 -down-> 53
35 -down-> 54
40 -down-> 55
40 -down-> 56
40 -down-> 57
40 -down-> 58
40 -down-> 59
40 -down-> 60
40 -down-> 61
40 -down-> 62
44 -down-> 63
44 -down-> 64
46 -down-> 65
46 -down-> 66
48 -down-> 67
48 -down-> 68
56 -down-> 69
56 -down-> 70
58 -down-> 71
58 -down-> 72
59 -down-> 73
59 -down-> 74
59 -down-> 75
59 -down-> 76
60 -down-> 77
60 -down-> 78
69 -down-> 79
69 -down-> 80
70 -down-> 81
70 -down-> 82
74 -down-> 83
74 -down-> 84
76 -down-> 85
76 -down-> 86
78 -down-> 87
78 -down-> 88
80 -down-> 89
80 -down-> 90
88 -down-> 91
88 -down-> 92
88 -down-> 93
91 -down-> 94
91 -down-> 95
93 -down-> 96
93 -down-> 97
95 -down-> 98
95 -down-> 99
95 -down-> 100
97 -down-> 101
97 -down-> 102
97 -down-> 103
@enduml
