@startuml ArbreSyntaxique
object "Procedure" as Procedure
object "traduisible" as traduisible
object "Bloc" as Bloc
object "Bloc" as Bloc1
object "Déclaration" as Declaration
object "Déclaration" as Declaration1
object "If" as InstructionIf
object "If" as InstructionIf3
object "a" as a
object "INTEGER" as INTEGER
object "b" as b
object "INTEGER" as INTEGER_
object "Operation" as Operation
object "Affectation" as Affectation
object "If" as InstructionIf1
object "Operation" as Operation8
object "Affectation" as Affectation5
object "a" as a_
object "EGAL" as EGAL
object "b" as b_
object "b" as b__
object "Operation" as Operation1
object "Operation" as Operation2
object "Bloc" as Bloc2
object "If" as InstructionIf2
object "a" as a________
object "EGAL" as EGAL_
object "b" as b__________
object "b" as b___________
object "Operation" as Operation9
object "b" as b___
object "PLUS" as PLUS
object "1" as 1
object "a" as a__
object "SUPERIEUR" as SUPERIEUR
object "b" as b____
object "Affectation" as Affectation1
object "Affectation" as Affectation2
object "Operation" as Operation5
object "Affectation" as Affectation3
object "Affectation" as Affectation4
object "b" as b____________
object "PLUS" as PLUS_____
object "1" as 1_____
object "b" as b_____
object "Operation" as Operation3
object "b" as b_______
object "Operation" as Operation4
object "a" as a___
object "INFERIEUR" as INFERIEUR
object "b" as b_________
object "a" as a____
object "Operation" as Operation6
object "a" as a______
object "Operation" as Operation7
object "b" as b______
object "PLUS" as PLUS_
object "1" as 1_
object "b" as b________
object "PLUS" as PLUS__
object "1" as 1__
object "a" as a_____
object "PLUS" as PLUS___
object "1" as 1___
object "a" as a_______
object "PLUS" as PLUS____
object "1" as 1____
Procedure -down-> traduisible
Procedure -down-> Bloc
Procedure -down-> Bloc1
Bloc -down-> Declaration
Bloc -down-> Declaration1
Bloc1 -down-> InstructionIf
Bloc1 -down-> InstructionIf3
Declaration -down-> a
Declaration -down-> INTEGER
Declaration1 -down-> b
Declaration1 -down-> INTEGER_
InstructionIf -down-> Operation
InstructionIf -down-> Affectation
InstructionIf -down-> InstructionIf1
InstructionIf3 -down-> Operation8
InstructionIf3 -down-> Affectation5
Operation -down-> a_
Operation -down-> EGAL
Operation -down-> b_
Affectation -down-> b__
Affectation -down-> Operation1
InstructionIf1 -down-> Operation2
InstructionIf1 -down-> Bloc2
InstructionIf1 -down-> InstructionIf2
Operation8 -down-> a________
Operation8 -down-> EGAL_
Operation8 -down-> b__________
Affectation5 -down-> b___________
Affectation5 -down-> Operation9
Operation1 -down-> b___
Operation1 -down-> PLUS
Operation1 -down-> 1
Operation2 -down-> a__
Operation2 -down-> SUPERIEUR
Operation2 -down-> b____
Bloc2 -down-> Affectation1
Bloc2 -down-> Affectation2
InstructionIf2 -down-> Operation5
InstructionIf2 -down-> Affectation3
InstructionIf2 -down-> Affectation4
Operation9 -down-> b____________
Operation9 -down-> PLUS_____
Operation9 -down-> 1_____
Affectation1 -down-> b_____
Affectation1 -down-> Operation3
Affectation2 -down-> b_______
Affectation2 -down-> Operation4
Operation5 -down-> a___
Operation5 -down-> INFERIEUR
Operation5 -down-> b_________
Affectation3 -down-> a____
Affectation3 -down-> Operation6
Affectation4 -down-> a______
Affectation4 -down-> Operation7
Operation3 -down-> b______
Operation3 -down-> PLUS_
Operation3 -down-> 1_
Operation4 -down-> b________
Operation4 -down-> PLUS__
Operation4 -down-> 1__
Operation6 -down-> a_____
Operation6 -down-> PLUS___
Operation6 -down-> 1___
Operation7 -down-> a_______
Operation7 -down-> PLUS____
Operation7 -down-> 1____
@enduml
